import fs from 'fs'
import { GedcomDataAccess } from './GedcomDataAccess.js'
import { createFamiliesMap } from './createFamiliesMap.js'
import { createPersonsMap } from './createPersonsMap.js'

// Access the GEDCOM Javascript data array
import { gedcomData } from './_GedcomDataJsArray.js'

const progName = (process.argv[1]).split('\\').pop()

// Create the GedcomDataAccess helper class to create Person and Family maps
const gda = new GedcomDataAccess(gedcomData)
writeMap(gda, createPersonsMap, '_PersonsMap.js', 'personsMap')
writeMap(gda, createFamiliesMap, '_FamiliesMap.js', 'familiesMap')

function writeMap(gda, method, fileName, varName) {
    const time1 = new Date()
    const map = method(gda)
    writeMapJsFile(map, fileName, varName)
    const time2 = new Date()
    console.log(`${progName} : Wrote '${fileName} with ${map.size} entries in ${time2-time1} msec`)
}

function writeMapJsFile(personsMap, outputName, varName) {
    let js = `// auto-generated by ${progName} on ${new Date().toLocaleString()}\n`
    js += `export const ${varName} = new Map(\n`
    js += JSON.stringify(Array.from(personsMap.entries()), null, 2)
    js += ')\n'

    // Write the Javascript to a file for later use
    fs.writeFile(outputName, js, function (err) {
        if (err) throw err
    })
}
