import fs from 'fs'
import { file2JsonArray } from '../index.js'
import { intFormat } from '../helpers/formatters.js'

const progName = (process.argv[1]).split('\\').pop()

const inputs = ['../tmp/Ancestry.ged', '../tmp/RootsMagic.ged']
const outputs = ['_gedcomDataAncestry.js', '_gedcomDataRootsMagic.js']
const started = new Date()

console.log(`${progName} ...`)
for (let i=0; i<inputs.length; i++) {
    const time1 = new Date()

    const lines = await file2JsonArray(inputs[i])
    const time2 = new Date()
    console.log(`    GEDCOM file          : '${inputs[i]}' has ${lines.length} records`)
    console.log(`        file2JsonArray() : ${intFormat(time2-time1)} msec`)

    writeFile(lines, outputs[i])
    const time3 = new Date()
    console.log(`        writeFile()      : ${intFormat(time3-time2)} msec`)
    console.log(`        created file     : '${outputs[i]}'`)
}
console.log(`Total elapsed time: ${(new Date()-started)} msec`)

function writeFile(lines, outputName, varName='_gedcomData') {
    // Create some Javascript from the text array
    let js = `// auto-generated by ${progName} on ${new Date().toLocaleString()}\n`
    js += `export const ${varName} = [\n`
    for(let i=0; i<lines.length; i++) js += JSON.stringify(lines[i]) + ',\n'
    js += ']\n'
    // Write the Javascript to a file for later use
    fs.writeFile(outputName, js, function (err) {
        if (err) throw err
    })
}
